DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS AGENTS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS ORDERPAYMENTS;


CREATE TABLE CUSTOMERS
(
	CUSTCODE int AUTO_INCREMENT,
	CUSTNAME CHAR not null,
	CUSTCITY CHAR not null,
	WORKINGAREA CHAR not null,
	CUSTCOUNTRY CHAR not null,
	GRADE CHAR not null,
	OPENINGAMT DOUBLE not null,
	RECEIVEAMT DOUBLE not null,
	PAYMENTAMT DOUBLE not null,
	OUTSTANDINGAMT DOUBLE not null,
	PHONE CHAR not null,
	AGENTCODE int not null
);

CREATE TABLE AGENTS (
    AGENTCODE INT AUTO_INCREMENT,
    AGENTNAME CHAR NOT NULL,
    WORKINGAREA CHAR NOT NULL,
    COMMISSION DOUBLE NOT NULL,
    PHONE CHAR NOT NULL,
    COUNTRY CHAR NOT NULL
);

CREATE TABLE ORDERS (
    ORDERNUM INT AUTO_INCREMENT,
    ORDERAMOUNT DOUBLE NOT NULL,
    ADVANCEAMOUNT DOUBLE NOT NULL,
    CUSTOMERCODE INT NOT NULL,
    ORDERDESCRIPTION CHAR NOT NULL
);

CREATE TABLE PAYMENTS (
    PAYMENTID INT NOT NULL,
    TYPE CHAR NOT NULL
);

CREATE TABLE ORDERPAYMENTS(
    ORDERNUM INT NOT NULL,
    PAYMENTID INT NOT NULL
);

